### PR TITLE
Added property inspection

### PR DESCRIPTION
**Pull request by rafleze**

### CODE REVIEW

**Comment by magopian** [comment]
Hello @rafleze,

thanks for taking the time to craft this PR ;)

I was wondering, is that "only" to list the "pk" property? Wouldn't it be more useful to have that returned in the list of attributes?

**Comment by 20tab** [comment]
Hello @magopian , I use property decorator in all my models and properties are not listed in any of the functions that you have defined.
pk is the default property for the models but if you add some property in your model this patch could be useful.
In every case thanks for this app because it solves my big problem. ;)

**Comment by 20tab** [comment]
Ops, I'm sorry. I'm @rafleze

**Comment by magopian** [comment]
awesome to hear that this app is useful to somebody ;)

I get it know, indeed, properties are not listed anywhere, so my question would be: would it make sense to list them in the "attributes", as they do appear (and are used) like attributes?

Or should they be in their own "type", as you did it? What do you think?

In any case, I'll need to pep8-ify your contribution before merging it. Thanks again for your work!

**Comment by gabbork** [comment]
We need properties separated because anyway they are not 'fields', they change dinamically etc, is better to know it when you use them.
We was working on a similar app cause in our workflow, django backend development and template design are strongly separated and developed by different people. With this app we don't need to produce schemas or diagrams to explain the designer how to use an object in the template, and he don't need to check inside the code. Cheers!

**Comment by magopian** [comment]
ok, I guess this makes sense.

Would you mind adding some tests for this, and making the code "pep8"? If that's too much burden, i'll do that as soon as I have a few minutes of spare time.

**Comment by gabbork** [comment]
@rafleze is less lazy than me...let's check if he will do it...

**Comment by magopian** [comment]
thanks @rafleze that looks nice (appart from the missing space), can you fix that and I'll merge?

**Comment by magopian** [comment]
Thanks a lot @rafleze!

**Pull request merged**
